use_frameworks!

platform :ios, '14.0'

target 'w3bstream_Example' do
  pod 'w3bstream', :path => '../'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'SnapKit', '~> 5.6.0'
  pod 'SwiftLocation/Core'
  pod 'RealmSwift'
  target 'w3bstream_Tests' do
    inherit! :search_paths
  end
end
