use_frameworks!

platform :ios, '10.0'

target 'w3bstream_Example' do
  pod 'w3bstream', :path => '../'
  target 'w3bstream_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
  end
end
